---
- name: stop docker
  systemd:
    name: "{{ service_name }}"
    state: stopped
  register: output

- debug:
    #var: output
    msg:
      - "{{ inventory_hostname }}: the {{ output.name }} service has been {{ output.state }}"
